version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    container_name: targetup_frontend
    restart: unless-stopped
    ports:
      - "5174:8080"
    environment:
      # This environment variable will be supplied by Coolify UI
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
